'on':
  push:
    branches:
      - prod-docker

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-project:latest
      - name: prepare the docker-compose run
        run: |
          mkdir vue-331
          cp docker-compose.yml vue-331/docker-compose.yml
          cd vue-331
          docker-compose -H ${{ secrets.HOST_SERVER }} pull
          docker-compose -H ${{ secrets.HOST_SERVER }} up -d
